# Generated by Django 5.2.13 on 2026-04-09 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('project', 'Project'), ('internal', 'Internal'), ('bank_holiday', 'Bank holiday'), ('annual_leave', 'Annual leave'), ('sick_leave', 'Sick leave'), ('other', 'Other')], max_length=40)),
                ('billing_type_default', models.CharField(blank=True, choices=[('internal', 'Internal'), ('billable', 'Billable'), ('non-billable', 'Non-billable')], max_length=20)),
                ('fixed_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('default_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_system_controlled_hours', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('activity_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='activities.activitycode')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'activity_code'],
                'constraints': [models.UniqueConstraint(fields=('user', 'activity_code'), name='unique_user_activity_assignment')],
            },
        ),
    ]
