# Generated by Django 5.2.13 on 2026-04-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycode',
            name='billing_type_default',
            field=models.CharField(blank=True, choices=[('internal', 'Internal'), ('billable', 'Billable'), ('non_billable', 'Non-billable')], max_length=20),
        ),
    ]
